### PR TITLE
Fix auth

### PR DESCRIPTION
**Pull request by DeliciousBounty**
Hey I fixed authentication and made some changes in auth.rs and conf.rs
In response to my issue  #109

### CODE REVIEW

**Review by GuyL99 — CHANGES_REQUESTED** [review]
In cherrybomb-engine/src/scan/active/http_client/auth.rs, you forgot to implement the custom auth type, and that's why it said the the 3 parts thingy is redundant, please implement it, plus I changed you toml file to have cherrybomb engine 0.1 and not path, we have to uplaod cherrybomb engine to crates.io before we move on, and that's for Raz to do.

**Comment by DeliciousBounty** [comment]
@GuyL99 ,
I did not forget to implement the custom auth type. 
Actually cherrybomb support for four  type of authentication:  basic, bearer, header, cookie.
You can see https://github.com/blst-security/cherrybomb/blob/fix_auth/cherrybomb-engine/src/scan/active/http_client/auth.rs
that the four type for authentication are implemented. ( see the "from_parts" function)

**Comment by GuyL99** [comment]
Why not include custom then?

**Comment by DeliciousBounty** [comment]
Raz called it header type instead of custom, it is work the same way. User provide header and value

**Comment by GuyL99** [comment]
Custom can be delivered by query or payload as a parameter...

**Comment by DeliciousBounty** [comment]
> Custom can be delivered by query or payload as a parameter...

I get it. 
So actually the new cherrybomb  CLI does not include custom authentication.
I implemented authentication in according to the new CLI.
maybe open an issue for it?

**Comment by RazMag** [comment]
Merged with dev, will be added to main in 1.0.1

**Pull request closed without merging**
