### PR TITLE
Creating Dockerfile

### LINKED ISSUE #16: 💡 Provide CherryBomb in an official Docker image
**Is your feature request related to a problem? Please describe.**
For users that want to run/use your tool in a CI/CD pipeline as part of a quality check, needing to install the tool locally may not always be an option.

**Describe the solution you'd like**
I would like to see this tool be made available in an official Docker image like many other CLI-based tools provide (ie. [AquaSec/Trivy](https://hub.docker.com/r/aquasec/trivy), [BridgeCrew/Checkov](https://hub.docker.com/r/bridgecrew/checkov), etc.).

**Describe alternatives you've considered**
A self-built container with the tool installed.

**Additional context**
None

### PR DESCRIPTION
**Pull request by prakharporwal**
Rust cli app dockerize using this article as reference 
https://dev.to/kevingimbel/how-to-distribute-a-rust-cli-tool-as-docker-image-5bgl

Fix #16

### CODE REVIEW

**Comment by prakharporwal** [comment]
@GuyL99 @DeliciousBounty @RazMag Working now I changed the base image to debian:stable and the docker image runs as expected.

**Review by BartvdBerkHU — CHANGES_REQUESTED** [review]
Hi,

Unfortunatly I was not able to build an image with this Dockerfile, getting this error.
````
 => ERROR [stage-1 2/2] COPY --from=builder /cherrybomb/target/release/cherrybomb .                                0.0s
------
 > [stage-1 2/2] COPY --from=builder /cherrybomb/target/release/cherrybomb .:
------
failed to compute cache key: "/cherrybomb/target/release/cherrybomb" not found: not found
````

Note: I use Docker Desktop and WSL Ubuntu on Windows.

This error might be related to using musl, but I have no experience with Rust, so i'm not sure.
When using the official image `rust:latest` as builder, this error disapears for me.

[This blog post](
https://kerkour.com/rust-small-docker-image) provides examples for smaller Rust container images. Musl also seems to slow down Rust application performance.

When using debian, I always use the slim variant, in this case you could use `stable-slim`.
Also provided in the blog post is an example to run the container as a non-priveledge user.

**Comment by prakharporwal** [comment]
Hi @BartvdBerkHU I have made those changes . Maybe try using it now.

**Comment by RazMag** [comment]
Hey! we've added docker support hosted on our repository. 
see here https://github.com/blst-security/cherrybomb#docker-container

Thank you for your help!

**Comment by prakharporwal** [comment]
@RazMag Did my code help? Would be grateful if you could point out my mistake and let me know what I could have improved on.

**Pull request closed without merging**
